version: '3.9'

services:

  api:
    build: ./backend
    container_name: aasi_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  php:
    image: php:8.2-apache
    container_name: aasi_php
    volumes:
      - ./frontend:/var/www/html
    ports:
      - "8080:80"