# Generated by Django 6.0.5 on 2026-05-26 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aparelho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo_anatomico', models.CharField(choices=[('RETRO', 'Retroauricular (BTE)'), ('INTRA', 'Intra-auricular (ITE/CIC)'), ('RIC', 'Receptor no Canal (RIC)')], max_length=10)),
                ('perda_indicada', models.CharField(choices=[('LEVE', 'Leve'), ('LEVE_MODERADA', 'Leve a Moderada'), ('MODERADA', 'Moderada'), ('MODERADA_SEVERA', 'Moderada a Severa'), ('SEVERA', 'Severa'), ('SEVERA_PROFUNDA', 'Severa a Profunda'), ('PROFUNDA', 'Profunda')], max_length=20)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='aparelhos/')),
                ('status', models.CharField(default='DISPONIVEL', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EMPRESA', 'Empresa'), ('DOADOR', 'Doador'), ('CANDIDATO', 'Candidato')], max_length=20)),
                ('cpf_cnpj', models.CharField(max_length=20, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
