# Generated by Django 6.0.5 on 2026-05-26 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laudo_exame', models.FileField(help_text='Anexe sua audiometria em PDF ou Imagem', upload_to='laudos/')),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando Análise'), ('APROVADO', 'Aprovado (Compatível)'), ('REPROVADO', 'Não Compatível')], default='AGUARDANDO', max_length=20)),
                ('data_candidatura', models.DateTimeField(auto_now_add=True)),
                ('aparelho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='devices.aparelho')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
