# Generated by Django 5.2.6 on 2026-05-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_candidatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparelho',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aparelho',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível para Doação'), ('AGUARDANDO', 'Aguardando Análise'), ('APROVADO', 'Aprovado para Doação'), ('DOADO', 'Doado')], default='AGUARDANDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando Análise'), ('APROVADO', 'Aprovado (Compatível)'), ('REPROVADO', 'Não Compatível'), ('ESCOLHIDO', 'Escolhido para Doação')], default='AGUARDANDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
