# Generated by Django 5.2.6 on 2026-06-06 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_aparelho_id_alter_aparelho_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aparelho',
            name='candidato',
        ),
        migrations.AddField(
            model_name='aparelho',
            name='candidato_escolhido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aparelhos_recebidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aparelho',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando Aprovação'), ('DISPONIVEL', 'Disponível'), ('DOADO', 'Doado'), ('REJEITADO', 'Rejeitado')], default='AGUARDANDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='laudo_exame',
            field=models.FileField(upload_to='laudos/'),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando Análise'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('ESCOLHIDO', 'Escolhido')], default='AGUARDANDO', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='candidatura',
            unique_together={('aparelho', 'candidato')},
        ),
    ]
